### ISSUE TITLE
Fallback img `srcset` and `alt` not being set

### ISSUE THREAD

**Issue by alexclarkofficial** [tevko/wp-tevko-responsive-images#15]
This could just be something only I am seeing, but the `srcset` and `alt` attributes in the fallback image are blank. I have a fix - let me know if you want a PR.

**Comment by tevko** [comment]
Hey, thanks for looking out! The rewrite of this plugin will be launched soon (a few weeks at most), so at this point, there's not much sense in maintaining this one
